name: version_checker
on: [pull_request_target]

jobs:
  check-apps-for-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo ${{ github.head_ref }}
          echo ${{ github.event.pull_request.head.sha }}
          git fetch origin +refs/heads/*:refs/remotes/origin/*
          git diff origin/${{ github.head_ref }}
